/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pontodevendas;

/**
 *
 * @author Pedro Dias
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private static ControladorProduto tabelaProduto;
    private static ControladorVenda tabelaVendas;
    private static ControladorItemVenda controladorItemVenda;
    
    public JanelaPrincipal() {
        initComponents();
        tabelaProduto = new ControladorProduto();
        controladorItemVenda = new ControladorItemVenda();
//        tabelaVendas = new ControladorVenda(controladorItemVenda, tabelaProduto);
        tabelaVendas = new ControladorVenda(tabelaProduto);
    }

    public static ControladorProduto obterControladorProduto(){
        return tabelaProduto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buProdutos = new javax.swing.JButton();
        buVendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buProdutos.setText("Produtos");
        buProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buProdutosActionPerformed(evt);
            }
        });

        buVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buVendas.setText("Vendas");
        buVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVendasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ponto de Vendas");

        buFechar.setText("Fechar");
        buFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buFechar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(buProdutos)
                .addGap(30, 30, 30)
                .addComponent(buVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(buFechar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buProdutosActionPerformed
        JanelaProdutos janelaProdutos = new JanelaProdutos(this, true, this.tabelaProduto);
        janelaProdutos.setLocationRelativeTo(null);
        janelaProdutos.setVisible(true);
    }//GEN-LAST:event_buProdutosActionPerformed

    private void buVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVendasActionPerformed
        JanelaVendas janelaVendas = new JanelaVendas(this, true, this.tabelaProduto, tabelaVendas);
        janelaVendas.setLocationRelativeTo(null);
        janelaVendas.setVisible(true);
    }//GEN-LAST:event_buVendasActionPerformed

    private void buFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buFecharActionPerformed
        dispose();
    }//GEN-LAST:event_buFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buFechar;
    private javax.swing.JButton buProdutos;
    private javax.swing.JButton buVendas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
