/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pontodevendas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Pedro Dias
 */
public class JanelaCadastroVenda extends javax.swing.JDialog {

    private ControladorVenda controladorVenda;
    private ControladorItemVenda controladorItemVenda;
    private ControladorProduto controladorProduto;
    private FormaPagamento formaPagamento;
    private Venda venda;
    
    
    public JanelaCadastroVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorItemVenda = new ControladorItemVenda();
        tabItemVenda.setModel(controladorItemVenda);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabItemVenda = new javax.swing.JTable();
        buCadastrarVenda = new javax.swing.JButton();
        buExcluirItem = new javax.swing.JButton();
        buAdicionarItem = new javax.swing.JButton();
        buFormaPagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Venda");

        tabItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabItemVenda);

        buCadastrarVenda.setText("Cadastrar Venda");
        buCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarVendaActionPerformed(evt);
            }
        });

        buExcluirItem.setText("Excluir Item");
        buExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirItemActionPerformed(evt);
            }
        });

        buAdicionarItem.setText("Adicionar Item");
        buAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAdicionarItemActionPerformed(evt);
            }
        });

        buFormaPagamento.setText("Forma de Pagamento");
        buFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buFormaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buExcluirItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buCadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(buAdicionarItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buAdicionarItem)
                        .addGap(18, 18, 18)
                        .addComponent(buExcluirItem)
                        .addGap(18, 18, 18)
                        .addComponent(buFormaPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buCadastrarVenda))
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarVendaActionPerformed

            //        int indice = tabProduto.getSelectedRow();
        //        if(indice >= 0){
            //            Produto produto = tabelaProduto.obterProduto(indice);
            //            JanelaCadastroProduto.executar(OperacaoCadastroProduto.consultar, produto);
            //        }
    }//GEN-LAST:event_buCadastrarVendaActionPerformed

    private void buExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirItemActionPerformed
                int indice = tabItemVenda.getSelectedRow();
                if(indice >= 0){
                    controladorItemVenda.removerItemVendaTabela(indice);
                }
        //          if(indice >= 0){
            //            tabelaProduto.removerProduto(indice);
            //        }
    }//GEN-LAST:event_buExcluirItemActionPerformed

    private void buAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAdicionarItemActionPerformed
//                ItemVenda itemVenda = new ItemVenda();
//                itemVenda.alterarNumeroItem(Integer.parseInt("21"));
//                itemVenda.alterarCodigo(Integer.parseInt("1111"));
//                itemVenda.alterarQntVenda(Integer.parseInt("1111"));
//                itemVenda.alterarPrecoProduto(Double.parseDouble("1111"));
//                itemVenda.alterarItemTotal(Double.parseDouble("1111"));
//                controladorItemVenda.incluirItemVendaTabela(itemVenda);

                ItemVenda itemVenda = new ItemVenda();
                
                if(JanelaAdicionarItem.executar(OperacaoAdicionarItemVenda.incluir, itemVenda)){
                        controladorItemVenda.incluirItemVendaTabela(itemVenda);
                    }
        
        
    }//GEN-LAST:event_buAdicionarItemActionPerformed

    private void buFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buFormaPagamentoActionPerformed
        FormaPagamento formaPagamento = new FormaPagamento();
        JanelaFormaPagamento.executar(venda, formaPagamento);
    }//GEN-LAST:event_buFormaPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaCadastroVenda dialog = new JanelaCadastroVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAdicionarItem;
    private javax.swing.JButton buCadastrarVenda;
    private javax.swing.JButton buExcluirItem;
    private javax.swing.JButton buFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabItemVenda;
    // End of variables declaration//GEN-END:variables
}
